import { render, screen,fireEvent } from '@testing-library/react';
import MyForm from './myform';
describe("testing UI",()=>{
    it("first test case",()=>{
        render(<MyForm/>)
        expect(screen.getByTestId('usernamelbl').textContent).toBe("enter user name")
        expect(screen.getByTestId('passwordlbl').textContent).toBe("enter password")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'amey'}})
        fireEvent.change(screen.getByTestId('passwrd'),{target:{value:'amey123'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("valid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'amey'}})
        fireEvent.change(screen.getByTestId('passwrd'),{target:{value:'amey12345'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("valid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'avinash'}})
        fireEvent.change(screen.getByTestId('passwrd'),{target:{value:'avinash12345'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("invalid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'@#$%%^&*'}})
        fireEvent.change(screen.getByTestId('password'),{target:{value:'12345678'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("invalid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'ameydharwa'}})
        fireEvent.change(screen.getByTestId('password'),{target:{value:'@#$%^&*!'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("invalid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'AVINASH'}})
        fireEvent.change(screen.getByTestId('password'),{target:{value:'Avinash12345'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("invalid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:'12345678'}})
        fireEvent.change(screen.getByTestId('password'),{target:{value:'Avinash12345'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
        expect(screen.getByTestId('msglbl').textContent).toBe("invalid user")
        fireEvent.change(screen.getByTestId('username'),{target:{value:''}})
        fireEvent.change(screen.getByTestId('password'),{target:{value:'AMEY12345'}})
        fireEvent.click(screen.getByTestId('submitctrl'))
    })
})